### ISSUE TITLE
Addon works in Palemoon, but is reported as running in compatibility mode.

### ISSUE THREAD

**Issue by dtoxic47** [RobertZenz/ThinBookmarks#3]
With firefox 57 just around the corner, are you maybe willing to support Pale Moon browser?

excellent extension and i think it would be a shame to stop the development.
I tested the latest version in Pale Moon 27.5.0 and it works excellent without any problems, pale moon only complains about it that it is running in compatibility mode. so if you are interested please head on to https://forum.palemoon.org/

Thx for this great extension, take care

**Comment by RobertZenz** [comment]
I've made the appropriate changes and tested it on the latest Palemoon release, so this will be in v1.4.

I'm also in talks to get the Thin* addons onto the Palemoon addons site, which will most likely happen within the next week or two or so.
